### ISSUE TITLE
2018年10月21日の課題

### ISSUE THREAD

**Issue by shoyan** [kazuya19840829/tutorial#3]
### 課題1
Userクラスのattr_accessorを消した状態で動かしてみてください。
その結果をコメントに書いてください。
Userクラスは `ruby user.rb` で実行できます。

### 課題2
initializeメソッドの `@name=name, @age=age` を削除した状態で動かしてみてください。
その結果をコメントに書いてください。

### 課題3
Userクラスをnewした後に年齢を23歳に変更してください。
こちらが参考になると思います。
https://ref.xaio.jp/ruby/classes/module/attr_accessor

### 課題4
attr_accessorを使わない状態で同じ動きをするようにUserクラスを修正してください。
コードの修正はmaster以外のブランチで行い、プルリクエストを出してください。

### 課題5
Userが未成年かどうかを判定するメソッドを作成してください。
コードの修正はmaster以外のブランチで行い、プルリクエストを出してください。

**Comment by kazuya19840829** [comment]
課題1

Traceback (most recent call last):
user.rb:11:in `<main>': undefined method `name' for #<User:0x00007f83591d0630 @name="Shohei", @age=33> (NoMethodError)

**Comment by kazuya19840829** [comment]
課題2

USER-no-MacBook-Air:ruby user$ ruby user.rb


USER-no-MacBook-Air:ruby user$

**Comment by shoyan** [comment]
@kazuya19840829 
課題1〜課題3 OKです 🙆 
課題1と課題2ですが、なぜそのような結果になったと考えますか？

**Comment by kazuya19840829** [comment]
課題1

Userクラス内のinitializeメソッドによって初期化されるインスタンス変数nameとageが
アクセサメソッドによってクラス外部からの読み書きが出来るよう定義づけがなされていないため
newメソッドによってUserクラスのオブジェクトであるuserの作成を試みても
メソッドの引数である"Shohei"と33は
インスタンス変数のnameとageに代入することが出来ない為

**Comment by kazuya19840829** [comment]
課題2

initializeメソッド内で引数であるnameとageを代入するインスタンス変数が
作成されていない。その為、userというオブジェクトを作成しても、newメソッド内の引数を渡すインスタンス変数がない為、存在しないインスタンス変数を出力することになる。よって何も表示されない。

**Comment by shoyan** [comment]
課題1ですが、正確にはインスタンス変数の@nameと@ageには代入自体は行えています。このことは次のコードで確認ができます。

```ruby
class User
  def initialize(name, age)
    @name = name
    @age = age
  end

  def name
    @name
  end

  def age
    @age
  end
end

user = User.new("Shohei", 33)
puts user.name
puts user.age
```

エラーになっている原因は`user.name` です。これは次のメッセージから確認ができます。

```ruby
➜  $ ruby ruby/user.rb
Traceback (most recent call last):
ruby/user.rb:11:in `<main>': undefined method `name' for #<User:0x00007fe85f0355f8 @name="Shohei", @age=33> (NoMethodError)
```

`ruby/user.rb:11`ですが、ruby/user.rbの11行目という意味です。
エラーメッセージに `undefined method `name'` と表示されています。これは、nameメソッドがないということです。

正しい答えは次の通りです。
attr_accessorを消したことによりnameメソッドが存在しなくなった。その結果NoMethodErrorが発生した。

課題2についてはOKです 🙆

**Comment by kazuya19840829** [comment]
課題1について、ちょっと理解に時間がかかってしまいましたが
attr_accessor :name, :ageを消したことで
nameとageという名前のアクセサメソッドが存在しなくなったということですね。
attr_accessor についての理解がまだまだでした。

**Comment by shoyan** [comment]
課題が完了したのでクローズします。
